#!/bin/sh
set -eu
test "$(uname -s)" = Linux && test "$(id -u)" = 0
action=$1
if test "$action" = identity; then
    hostname
    cat /proc/sys/kernel/random/boot_id
    docker info --format '{{.ID}}'
    docker version --format '{{.Server.Arch}}'
    exit
fi
if test "$action" = prepare; then
    root=$(mktemp -d /tmp/dispatch-sweep.XXXXXXXX)
    chmod 700 "$root"
    mkdir "$root/state" "$root/fs"
    chmod 700 "$root/state" "$root/fs"
    truncate -s 256M "$root/disk"
    device=$(losetup --find --show "$root/disk")
    printf '%s\n' "$device" > "$root/device"
    # Only this new file-backed device is formatted. Retain the root on setup
    # failure so quota or mount uncertainty cannot authorize unrelated cleanup.
    mkfs.ext4 -q -O project,quota -E quotatype=prjquota "$device"
    mount -t ext4 -o prjquota,nosuid,nodev "$device" "$root/fs"
    chmod 700 "$root/fs"
    printf '%s\n' "$root"
    exit
fi
root=$2
case "$root" in /tmp/dispatch-sweep.*) ;; *) exit 1 ;; esac
case "${root#/tmp/dispatch-sweep.}" in ''|*[!a-zA-Z0-9]*) exit 1 ;; esac
test -d "$root" && test "$(stat -c %u "$root")" = 0
case "$action" in
    configure)
        # This archive is generated by the host test, never by a workload.
        # Certificate keys stay in this root-only fixture and never reach logs.
        tar -xf - -C "$root"
        /tmp/dispatch-worker init-scratch --config "$root/worker.json"
        ;;
    run)
        printf '%s\n' "$$" > "$root/agent.pid"
        exec /tmp/dispatch-worker run --config "$root/worker.json"
        ;;
    stop)
        if test -f "$root/agent.pid"; then
            pid=$(cat "$root/agent.pid")
            case "$pid" in ''|*[!0-9]*) exit 1 ;; esac
            if test -d "/proc/$pid"; then
                # A reused PID cannot authorize killing a different process.
                tr '\000' '\n' < "/proc/$pid/cmdline" | grep -Fx "$root/worker.json" >/dev/null
                kill -KILL "$pid"
            fi
        fi
        ;;
    inspect)
        id=$3
        case "$id" in ''|*[!a-f0-9]*) exit 1 ;; esac
        test "$(docker inspect --format '{{index .Config.Labels "dev.dispatch.worker"}}' "$id")" = "$(cat "$root/worker-id")"
        docker inspect --format '{{.State.Running}}' "$id"
        ;;
    cleanup)
        # Failed inventory or removal retains the mount and allocator evidence.
        # Only the unpredictable enrolled identity in this fixture is a target.
        worker=$(cat "$root/worker-id")
        case "$worker" in ''|*[!a-f0-9-]*) exit 1 ;; esac
        ids=$(docker ps -aq --filter "label=dev.dispatch.worker=$worker")
        for id in $ids; do docker rm -f "$id" >/dev/null; done
        if mountpoint -q "$root/fs"; then umount "$root/fs"; fi
        losetup -d "$(cat "$root/device")"
        rm -rf "$root"
        ;;
    *) exit 1 ;;
esac
