[package]
name = "dispatch-worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
libc = "=0.2.189"
ring = "=0.17.14"
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"
dispatch-protocol = { path = "../protocol" }
prost = "=0.14.3"
tonic = { version = "=0.14.6", features = ["tls-ring"] }
tokio = { version = "=1.53.1", features = ["rt-multi-thread", "macros", "time"] }
